version: "3"
services:
  server:
    image: rails:5.0.1
    restart: always
    ports:
      - 3333:3000
    container_name: server
    depends_on:
      - db
    volumes:
      - ./server:/app/server
    working_dir: /app/server
    tty: true
    entrypoint: bash

  client:
    image: node:12.18.4-alpine
    restart: always
    ports:
      - 3000:3000
    container_name: client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
    working_dir: /app/client
    stdin_open: true
    command: sh -c "yarn install && yarn start"

  db:
    container_name: mysql
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "reader"
      MYSQL_PASSWORD: "123123"
      MYSQL_DATABASE: "fruits"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
