version: "3"
services:
  server:
    image: gradle:jdk14
    restart: always
    ports:
      - 3333:3000
    container_name: server
    depends_on:
      - db
    volumes:
      - ./server-java:/app/server
    working_dir: /app/server
    command: gradle run
    # tty: true
    # entrypoint: bash

  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000
    container_name: client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
    working_dir: /app/client
    stdin_open: true
    command: yarn start

  db:
    container_name: postgres
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server-java/vendor/init-database:/docker-entrypoint-initdb.d
    environment: 
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: postgres
      POSTGRES_DB: fruits_dev

volumes: 
  postgres-data: