version: "3"
services:
  server:
    image: ruby:2.7.2
    restart: always
    ports:
      - 3333:3000
    container_name: server
    depends_on:
      - db
    volumes:
      - ./server:/app/server
    working_dir: /app/server
    # command: bash -c "bundle install && rake db:migrate && rails s -b 0.0.0.0"
    tty: true
    entrypoint: sh

  client:
    image: node:12.18.4-alpine
    restart: always
    ports:
      - 3000:3000
    container_name: client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
    working_dir: /app/client
    stdin_open: true
    command: sh -c "yarn install && yarn start"

  db:
    container_name: postgres
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: 123123
