version: "3"
services:
  server:
    build:
      context: ./server
    restart: always
    ports:
      - 3333:3000
    container_name: server
    depends_on:
      - db
    volumes:
      - ./server:/app/server
    working_dir: /app/server
    command: rails s -b 0.0.0.0

  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000
    container_name: client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
    working_dir: /app/client
    stdin_open: true
    command: yarn start

  db:
    container_name: postgres
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: 123123
